# Generated by Django 5.2.8 on 2025-12-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_city_profile_gender_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловік'), ('female', 'Жінка'), ('other', 'Стать не вказана')], max_length=10, null=True, verbose_name='Стать'),
        ),
    ]
