# Generated by Django 5.2.8 on 2025-12-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
