# Generated by Django 5.2.8 on 2025-12-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Контакти або примітка'),
        ),
    ]
