# Generated by Django 5.2.8 on 2025-12-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_booking_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
