# Generated by Django 5.2.8 on 2025-12-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_booking_client_google_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_google_event_id',
            field=models.CharField(blank=True, help_text='ID події в календарі клієнта', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='ID події в календарі ментора', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ціна на момент бронювання (фіксується)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оцінка (1-5)'),
        ),
    ]
