name: Django CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          SECRET_KEY: "ci-test-secret-key-just-for-github-actions"
          SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "fake-key"
          SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "fake-secret"
        run: |
          pytest